# Generated by Django 3.1 on 2020-12-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20201213_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
