# Generated by Django 3.1 on 2020-12-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_auto_20201213_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
