# Generated by Django 3.1 on 2020-12-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0010_recommend_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='user',
        ),
    ]
