# Generated by Django 3.1 on 2020-12-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0012_recommend_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='user',
        ),
    ]
