# Generated by Django 3.1 on 2020-11-27 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aljoadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=50, verbose_name='FOOD_NAME')),
                ('recipe', models.CharField(max_length=100, verbose_name='RECIPE')),
                ('hashtag', models.CharField(blank=True, max_length=100, verbose_name='HASHTAG')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m', verbose_name='IMAGE')),
                ('good', models.IntegerField(blank=True, verbose_name='GOOD')),
                ('bad', models.IntegerField(blank=True, verbose_name='BAD')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER')),
            ],
            options={
                'verbose_name': 'aljoadmin',
                'verbose_name_plural': 'aljoadmins',
                'db_table': 'aljoadmin',
                'ordering': ('-modify_dt',),
            },
        ),
    ]
