# Generated by Django 3.1 on 2020-11-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aljoadmin', '0002_aljoadmincomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AljoadminComment',
        ),
    ]
