# Generated by Django 3.1 on 2020-11-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aljoadmin', '0004_aljoadmin_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aljoadmin',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='one word for title alias.', unique=True, verbose_name='SLUG'),
        ),
    ]
