# Generated by Django 3.1 on 2020-11-29 13:33

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('aljoadmin', '0006_auto_20201129_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='aljoadmin',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
