# Generated by Django 3.1 on 2020-11-30 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aljoadmin', '0007_aljoadmin_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aljoadmin',
            name='bad',
        ),
        migrations.RemoveField(
            model_name='aljoadmin',
            name='hashtag',
        ),
    ]
