# Generated by Django 3.1 on 2020-11-30 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aljoadmin', '0008_auto_20201130_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='COMMENT')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='CREATE DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='MODIFY DATE')),
                ('aljo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aljoadmin.aljoadmin')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_dt'],
            },
        ),
    ]
