# Generated by Django 3.1 on 2020-11-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aljoadmin', '0010_auto_20201130_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aljoadmin',
            new_name='post',
        ),
    ]
