# Generated by Django 3.1 on 2020-11-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aljoadmin', '0012_auto_20201130_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='user',
        ),
    ]
