# Generated by Django 3.1 on 2020-11-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aljoadmin', '0013_auto_20201130_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='writer',
        ),
    ]
