# Generated by Django 3.1 on 2020-11-30 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aljoadmin', '0014_auto_20201130_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='CREATE DATE')),
                ('aljo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aljoadmin.aljoadmin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_dt'],
                'unique_together': {('aljo', 'user')},
            },
        ),
    ]
