# Generated by Django 3.1 on 2020-11-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aljoadmin', '0015_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
