# Generated by Django 3.1 on 2020-11-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aljoadmin', '0017_aljoadmin_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aljoadmin',
            name='like_users',
        ),
    ]
