# Generated by Django 3.1 on 2020-11-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aljoadmin', '0018_remove_aljoadmin_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='aljoadmin',
            name='brand',
            field=models.CharField(max_length=30, null=True, verbose_name='BRAND'),
        ),
    ]
