# Generated by Django 3.1 on 2020-12-01 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aljoadmin', '0022_aljoadmin_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aljoadmin',
            name='like_users',
        ),
        migrations.AddField(
            model_name='aljoadmin',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
