# Generated by Django 3.1 on 2020-12-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aljoadmin', '0023_auto_20201201_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aljoadmin',
            name='like',
        ),
    ]
