# Generated by Django 3.1 on 2020-12-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aljoadmin', '0025_aljoadmin_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aljoadmin',
            name='good',
        ),
    ]
