# Generated by Django 3.1 on 2020-11-29 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aljouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodnameU', models.CharField(max_length=50, verbose_name='FOOD_NAME')),
                ('recipeU', models.CharField(max_length=100, verbose_name='RECIPE')),
                ('hashtagU', models.CharField(blank=True, max_length=100, verbose_name='HASHTAG')),
                ('imageU', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m', verbose_name='IMAGE')),
                ('goodU', models.IntegerField(blank=True, verbose_name='GOOD')),
                ('badU', models.IntegerField(blank=True, verbose_name='BAD')),
                ('create_dtU', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE')),
                ('modify_dtU', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
                ('ownerU', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER')),
            ],
            options={
                'verbose_name': 'aljouser',
                'verbose_name_plural': 'aljousers',
                'db_table': 'aljouser',
                'ordering': ('-modify_dtU',),
            },
        ),
    ]
