# Generated by Django 3.1 on 2020-11-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aljouser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aljouser',
            name='slugU',
            field=models.SlugField(allow_unicode=True, help_text='one word for title alias.', null=True, unique=True, verbose_name='SLUG'),
        ),
    ]
