# Generated by Django 3.1 on 2020-11-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aljouser', '0002_aljouser_slugu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aljouser',
            options={'ordering': ('-modify_dt',), 'verbose_name': 'aljouser', 'verbose_name_plural': 'aljousers'},
        ),
        migrations.RenameField(
            model_name='aljouser',
            old_name='badU',
            new_name='bad',
        ),
        migrations.RenameField(
            model_name='aljouser',
            old_name='create_dtU',
            new_name='create_dt',
        ),
        migrations.RenameField(
            model_name='aljouser',
            old_name='foodnameU',
            new_name='foodname',
        ),
        migrations.RenameField(
            model_name='aljouser',
            old_name='goodU',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='aljouser',
            old_name='hashtagU',
            new_name='hashtag',
        ),
        migrations.RenameField(
            model_name='aljouser',
            old_name='imageU',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='aljouser',
            old_name='modify_dtU',
            new_name='modify_dt',
        ),
        migrations.RenameField(
            model_name='aljouser',
            old_name='ownerU',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='aljouser',
            old_name='recipeU',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='aljouser',
            old_name='slugU',
            new_name='slug',
        ),
    ]
