# Generated by Django 3.1 on 2020-11-29 14:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('aljouser', '0003_auto_20201129_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aljouser',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='aljouser',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
