# Generated by Django 3.1 on 2020-11-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aljouser', '0004_auto_20201129_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aljouser',
            name='bad',
        ),
    ]
