# Generated by Django 3.1 on 2020-11-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aljouser', '0006_commentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='aljouser',
            name='brand',
            field=models.CharField(max_length=30, null=True, verbose_name='BRAND'),
        ),
        migrations.AddField(
            model_name='aljouser',
            name='role',
            field=models.CharField(max_length=10, null=True, verbose_name='BRAND'),
        ),
    ]
