# Generated by Django 3.1 on 2020-11-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aljouser', '0007_auto_20201130_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aljouser',
            name='role',
            field=models.CharField(max_length=10, null=True, verbose_name='ROLE'),
        ),
    ]
