# Generated by Django 3.1 on 2020-12-01 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aljouser', '0008_auto_20201130_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aljouser',
            name='good',
        ),
        migrations.AddField(
            model_name='aljouser',
            name='like_users',
            field=models.ManyToManyField(related_name='like_postsUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
