# Generated by Django 3.1 on 2020-12-02 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aljouser', '0010_auto_20201202_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aljouser',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_postsUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
