# Generated by Django 3.1 on 2020-12-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aljouser', '0011_auto_20201202_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='aljouser',
            name='like',
            field=models.IntegerField(null=True, verbose_name='LIKE'),
        ),
        migrations.AlterField(
            model_name='aljouser',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m', verbose_name='IMAGE'),
        ),
        migrations.AlterField(
            model_name='aljouser',
            name='recipe',
            field=models.TextField(verbose_name='RECIPE'),
        ),
    ]
