# Generated by Django 3.1 on 2020-12-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aljouser', '0012_auto_20201205_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aljouser',
            options={'ordering': ('-create_dt',), 'verbose_name': 'aljouser', 'verbose_name_plural': 'aljousers'},
        ),
        migrations.RemoveField(
            model_name='aljouser',
            name='like',
        ),
    ]
