# Generated by Django 3.1 on 2020-12-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aljouser', '0013_auto_20201205_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='aljouser',
            name='like',
            field=models.IntegerField(null=True, verbose_name='LIKE'),
        ),
    ]
