# Generated by Django 3.1 on 2020-12-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aljouser', '0014_aljouser_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aljouser',
            name='like',
        ),
    ]
