# Generated by Django 3.1 on 2020-12-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aljouser', '0016_aljouser_likeu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aljouser',
            name='likeU',
        ),
    ]
