# Generated by Django 3.1 on 2020-12-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aljouser', '0017_remove_aljouser_likeu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aljouser',
            name='slug',
        ),
    ]
